const PDFDocument = require('pdfkit');

const COLORS = { heading: '#0f172a', label: '#64748b', body: '#334155', accent: '#2563eb', rule: '#e2e8f0' };

const drawSectionTitle = (doc, text) => {
  doc.moveDown(1.2);
  doc.font('Helvetica-Bold').fontSize(9).fillColor(COLORS.accent).text(text.toUpperCase(), { characterSpacing: 1 });
  doc.moveDown(0.4);
  const y = doc.y;
  doc.strokeColor(COLORS.rule).lineWidth(1).moveTo(doc.page.margins.left, y).lineTo(doc.page.width - doc.page.margins.right, y).stroke();
  doc.moveDown(0.6);
};

const drawField = (doc, label, value) => {
  doc.font('Helvetica').fontSize(8).fillColor(COLORS.label).text(label.toUpperCase(), { characterSpacing: 0.6 });
  doc.font('Helvetica').fontSize(11).fillColor(COLORS.body).text(value || '—');
  doc.moveDown(0.5);
};

/**
 * Streams a final thesis submission cover sheet to the given response.
 * `submission` must have proposal, thesisVersion, plagiarismReport and submittedBy populated.
 */
const buildSubmissionPdf = (submission, res) => {
  const doc = new PDFDocument({ size: 'A4', margin: 56 });
  doc.pipe(res);

  const proposal = submission.proposal || {};
  const version = submission.thesisVersion || {};
  const plagiarism = submission.plagiarismReport;

  doc.font('Helvetica-Bold').fontSize(20).fillColor(COLORS.heading).text('ResearchHub');
  doc.font('Helvetica').fontSize(10).fillColor(COLORS.label).text('University Thesis & Research Collaboration Platform');
  doc.moveDown(1);
  doc.font('Helvetica-Bold').fontSize(15).fillColor(COLORS.heading).text('Final Thesis Submission Cover Sheet');

  drawSectionTitle(doc, 'Thesis Details');
  drawField(doc, 'Title', proposal.title);
  drawField(doc, 'Thesis ID', String(proposal._id || ''));
  drawField(doc, 'Department', proposal.supervisor?.department);

  drawSectionTitle(doc, 'Students');
  const students = Array.isArray(proposal.students) ? proposal.students : [];
  if (students.length === 0) {
    doc.font('Helvetica').fontSize(11).fillColor(COLORS.body).text('—');
  } else {
    students.forEach((s) => {
      doc.font('Helvetica').fontSize(11).fillColor(COLORS.body).text(`${s.name}  (${s.studentId})`);
    });
  }

  drawSectionTitle(doc, 'Supervision');
  drawField(doc, 'Supervisor', proposal.supervisor?.name);
  if (proposal.coSupervisor?.name) drawField(doc, 'Co-Supervisor', proposal.coSupervisor.name);

  drawSectionTitle(doc, 'Abstract');
  doc.font('Helvetica').fontSize(10.5).fillColor(COLORS.body).text(submission.abstract, { align: 'justify', lineGap: 2 });

  if (submission.keywords?.length) {
    drawSectionTitle(doc, 'Keywords');
    doc.font('Helvetica').fontSize(10.5).fillColor(COLORS.body).text(submission.keywords.join(', '));
  }

  drawSectionTitle(doc, 'Submitted Document');
  drawField(doc, 'Version', version.versionNumber ? `Version ${version.versionNumber}` : '—');
  drawField(doc, 'File', version.file?.originalName);
  drawField(
    doc,
    'Plagiarism Check',
    plagiarism ? `${plagiarism.similarityPercentage}% similarity (${plagiarism.toolName})` : 'Not attached'
  );

  drawSectionTitle(doc, 'Declaration');
  doc.font('Helvetica').fontSize(10).fillColor(COLORS.body).text(
    'I hereby declare that this thesis is my own original work, that it has not been submitted for any other degree, and that all sources used have been properly acknowledged.',
    { align: 'justify', lineGap: 2 }
  );

  drawSectionTitle(doc, 'Submission Record');
  drawField(doc, 'Submitted By', submission.submittedBy?.name);
  drawField(doc, 'Submitted On', new Date(submission.createdAt).toLocaleString());
  drawField(doc, 'Status', String(submission.status || '').toUpperCase());
  if (submission.reviewComment) drawField(doc, 'Supervisor Remarks', submission.reviewComment);

  doc.moveDown(2.5);
  const signatureY = doc.y;
  const left = doc.page.margins.left;
  const right = doc.page.width - doc.page.margins.right;
  const lineWidth = 180;

  doc.strokeColor(COLORS.rule).lineWidth(1);
  doc.moveTo(left, signatureY).lineTo(left + lineWidth, signatureY).stroke();
  doc.moveTo(right - lineWidth, signatureY).lineTo(right, signatureY).stroke();
  doc.font('Helvetica').fontSize(9).fillColor(COLORS.label);
  doc.text('Student Signature', left, signatureY + 6, { width: lineWidth });
  doc.text('Supervisor Signature', right - lineWidth, signatureY + 6, { width: lineWidth, align: 'right' });

  doc.fontSize(8).fillColor(COLORS.label).text(
    `Generated by ResearchHub on ${new Date().toLocaleString()}`,
    left,
    doc.page.height - doc.page.margins.bottom - 12,
    { width: right - left, align: 'center' }
  );

  doc.end();
};

module.exports = { buildSubmissionPdf };
